### ISSUE TITLE
Recover entire folder

### ISSUE THREAD

**Issue by cryzed** [akalongman/sublimetext-autobackups#26]
Hey, I recently accidentally deleted a project folder of mine of which I had no backup (only partial file backups created by your plugin). I figured I could write a script that attempts to use all these partial backups to restore the latest version of the project I had on my disk. [This](https://gist.github.com/cryzed/144475d411791b4573bf) was the result. I thought maybe you or someone else would find it useful. I can't guarantee that it will work for every project or system, but it did for mine.

The first argument passed to the script should be the path to the backup folder used by the plugin, and the second argument the path of the project that you want to recover.

**Comment by akalongman** [comment]
Can you implement this feature in AutoBackups? Send me pull request if you will do

**Comment by cryzed** [comment]
Is there something you disagree with?

**Comment by akalongman** [comment]
No, no, I dont have time for review pull request for now. But anyway thank you for supporting. I will try review soon
