### ISSUE TITLE
Excluded extensions

### ISSUE THREAD

**Issue by akalongman** [akalongman/sublimetext-autobackups#3]
Add exclude extensions in settings

**Comment by lichtamberg** [comment]
Yeah, please... I would pay you 10$ via bitcoins/changetip for implementing this?

**Comment by akalongman** [comment]
Yes, I will implement this feature in next release

**Comment by lichtamberg** [comment]
Great, thanks! Please close this issue when it's finished and I will send you the tip.. And thanks for your great plugin, it prevented me already several times of big troubles...!

**Comment by akalongman** [comment]
You can check new version [2.3.3](https://github.com/akalongman/sublimetext-autobackups/releases/tag/2.3.3)
Comitted 10 minutes ago and I think in package manager will be available in few hours

**Comment by lichtamberg** [comment]
@akalongman , thanks!

Could you add this feature also to the readme and give an example in the default package setting?
Then I will send you the tip!

Thanks!

**Comment by akalongman** [comment]
@lichtamberg sorry, my fault :) Done

**Comment by lichtamberg** [comment]
@akalongman , thanks for your great work! 
Here is your tip $10, @ChangeTip should deliver it to you! :)

**Comment by changetip** [comment]
Hi @akalongman, @lichtamberg sent you a Bitcoin tip worth 41,644 bits ($10.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/829691)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by akalongman** [comment]
Thank you, I appreciate your support!

**Comment by lichtamberg** [comment]
Thanks, works great! :)
